### PR TITLE
Fixes the Grid / Scrolling Issue #42

### LINKED ISSUE #42: The list of paired students should be its own scrollable component
The list of paired students should be its own scrollable component, separate from the Chatbox.  Scrolling down the chatbox should not scroll down the list of paired students. Similiarly, scrolling down the list of Paired Students should not scroll down the chatbox. 

image

### PR DESCRIPTION
**Pull request by zachlankton**
Moved the `PairedStudentList` in the Grid Item with `UnpairedStudentList` so that they will stay together when the chat on the right column grows.

Made some CSS changes to the ChatBox/Conversation Area to cap the height to 260px and overflow the chat area.  This will keep the user from needing to scroll the entire page to see the chat.

Created a style.css for next.js global styles and added scrollbar css to make scrollbars consistent across platforms (make windows scrollbars prettier)

Refactored the `ScrollDown` behavior to work with the changes made above.  Now just the chat area scrolls down when new messages are sent/received. Also moved the call to `ScrollDown` into a `useEffect` block to make sure that it happens after state is updated.  Without this the scroll down did not work reliably.

Closes #42

### CODE REVIEW

File: src/components/pages/StudentsPage/SendMessages.tsx [hunk 1]
```diff
@@ -24,17 +18,21 @@ export default function SendMessages({
...
       }
     }
-    messageInput.current.focus();
+
   }
 
+  useEffect(() => {
+    scrollDown();
+  }, [chat.conversation]);
+
```
Comment (mssiegel) [inline src/components/pages/StudentsPage/SendMessages.tsx:35]: Since there is a useEffect scrolling down in Student/Conversation, this useEffect might not be necessary.

File: src/components/pages/TeachersPage/Conversation.tsx [hunk 2]
```diff
@@ -7,6 +8,12 @@ import { filterWords } from '@utils/classrooms';
 
 export default function Conversation({ chat }) {
   const [student1, student2] = chat.studentPair;
+  const lastMessage = useRef(null);
+
+  useEffect(() => {
+    if (lastMessage.current)
```
Comment (mssiegel) [inline src/components/pages/TeachersPage/Conversation.tsx:14]: scrollDown() can be put into its own utility function in classrooms util file. So can be used for both Students and Teachers.

File: src/components/pages/StudentsPage/Conversation.tsx [hunk 3]
```diff
@@ -6,7 +6,13 @@ import { useEffect } from 'react';
 import conversationCSS from './Conversation.css';
 import { filterWords } from '@utils/classrooms';
 
-export default function Conversation({ socket, chat, setChat, scrollDown }) {
+export default function Conversation({
+  socket,
+  chat,
+  setChat,
+  scrollDown,
+  lastMessage,
```
Comment (mssiegel) [inline src/components/pages/StudentsPage/Conversation.tsx:14]: lastMessage is passed in but is not used.

**Review by mssiegel — CHANGES_REQUESTED** [review]
Once above comments are addressed, go ahead and merge.
